# Generated by Django 5.1.7 on 2025-03-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьер'), ('digital', 'Цифровая доставка')], default='pickup', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидайте доставку'), ('confirmed', 'Подтверждён'), ('canceled', 'Отменён'), ('delivered', 'Доставлен')], default='pending', max_length=50),
        ),
    ]
